pointcloud:
  file_path: "./input.ply"  # 点云文件路径
  file_format: "ply"  # 点云文件格式，可以选择 pcd 或 ply

mapping:
    voxel_size: 2.0
    max_layer: 4                # 4 layer, 0, 1, 2, 3
    outliers_threshold: 5
    plannar_threshold: 0.01
    
